#ifndef CMPSC_472_RDWRBINARY_FILE_CMPSC472_BINARYFILE_DATA_BIN_H
#define CMPSC_472_RDWRBINARY_FILE_CMPSC472_BINARYFILE_DATA_BIN_H

#define FILENAME "BinaryMsg.txt"
#define NUM_RECORDS 5

// Structure definition
struct Data {
    int record;
    int value;
};

#endif CMPSC_472_RDWRBINARY_FILE_CMPSC472_BINARYFILE_DATA_BIN_H

